# Generated by Django 5.0.3 on 2024-04-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_courserating_course_alter_courserating_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '8. Course Ratings'},
        ),
    ]
