# Generated by Django 5.0.3 on 2024-04-20 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_courserating_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfavoritecourse',
            options={},
        ),
    ]
