# Generated by Django 5.0.3 on 2024-04-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_studentfavoritecourse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfavoritecourse',
            options={'verbose_name_plural': '7. Student Favorite Courses'},
        ),
    ]
