# Generated by Django 5.0.3 on 2024-04-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_attemptquiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attemptquiz',
            options={'verbose_name_plural': '14. Attempted Questions'},
        ),
        migrations.AddField(
            model_name='attemptquiz',
            name='right_ans',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
