# Generated by Django 5.0.3 on 2024-05-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_student_otp_digit_student_verify_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_via_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='login_via_otp',
            field=models.BooleanField(default=False),
        ),
    ]
